// <auto-generated />
// Arquivo gerado automaticamente pelo Entity Framework Core - NÃO EDITAR MANUALMENTE
// Representa um snapshot (instantâneo) do modelo de dados atual
// Importa o Entity Framework Core para funcionalidades de ORM
using Microsoft.EntityFrameworkCore;
// Importa classes de infraestrutura do Entity Framework
using Microsoft.EntityFrameworkCore.Infrastructure;
// Importa classes para conversão de valores entre tipos .NET e banco de dados
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
// Importa o contexto de dados da aplicação LivrariaApi
using LivrariaApi.Data;

// Desabilita warnings de nullability para este arquivo auto-gerado
#nullable disable

// Define o namespace específico para as migrações da LivrariaApi
namespace LivrariaApi.Migrations
{
    // Atributo que associa este snapshot ao contexto DataContext
    [DbContext(typeof(DataContext))]
    // Classe partial que representa o estado atual completo do modelo de dados
    // ModelSnapshot é usado pelo EF para comparar o estado atual com migrações pendentes
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        // Método que constrói o modelo de dados atual (estado mais recente)
        // Representa como o banco de dados está estruturado atualmente
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
// Suprime warnings específicos relacionados a APIs obsoletas
#pragma warning disable 612, 618
            // Define a versão do Entity Framework Core usada
            modelBuilder.HasAnnotation("ProductVersion", "6.0.31");

            // Configura a entidade Livro e seu mapeamento atual no banco de dados
            modelBuilder.Entity("LivrariaApi.Livro", b =>
                {
                    // Configura a propriedade Id como chave primária auto-incremental
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd() // Valor gerado automaticamente na inserção
                        .HasColumnType("INTEGER"); // Tipo da coluna no SQLite

                    // Configura a propriedade Ano como coluna INTEGER
                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER"); // Tipo da coluna no SQLite

                    // Configura a propriedade Autor como coluna TEXT obrigatória
                    b.Property<string>("Autor")
                        .IsRequired() // Campo não pode ser nulo
                        .HasMaxLength(200) // Tamanho máximo de 200 caracteres
                        .HasColumnType("TEXT"); // Tipo da coluna no SQLite

                    // Configura a propriedade Titulo como coluna TEXT obrigatória
                    b.Property<string>("Titulo")
                        .IsRequired() // Campo não pode ser nulo
                        .HasMaxLength(200) // Tamanho máximo de 200 caracteres
                        .HasColumnType("TEXT"); // Tipo da coluna no SQLite

                    // Define Id como chave primária da tabela
                    b.HasKey("Id");

                    // Mapeia a entidade para a tabela "Livros" no banco de dados
                    b.ToTable("Livros");
                });
// Restaura warnings que foram suprimidos anteriormente
#pragma warning restore 612, 618
        } // Fim do método BuildModel
    } // Fim da classe DataContextModelSnapshot
} // Fim do namespace LivrariaApi.Migrations
